name = "NaturalEarth"
uuid = "436b0209-26ab-4e65-94a9-6526d86fea76"
authors = ["Haakon Ludvig Langeland Ervik (@haakon-e), Anshul Singhvi <anshulsinghvi@gmail.com>, and contributors"]
version = "0.1.0"

[deps]
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
JSON3 = "1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
